pull_request_rules:
  - name: automatic update
    conditions:
      - -conflict # skip PRs with conflicts
      - -draft # filter-out GH draft PRs
    actions:
      update:
  - name: Automatic merge
    conditions:
      - "#approved-reviews-by>=2"
      - check-success=lint (ubuntu-latest, 3.10)
      - check-success=build_test_job (ubuntu-latest, 3.8, ray)
      - check-success=build_test_job (ubuntu-latest, 3.9, ray)
      - check-success=build_test_job (ubuntu-latest, 3.10, ray)
      - check-success=build_test_job (ubuntu-latest, 3.11, ray)
      - check-success=codecov/project
      - base=main
    actions:
      merge:
        method: squash
